spring:
  profiles:
<<<<<<< HEAD
    active: dev
=======
    active:
>>>>>>> c349e453c9c2cebdf8a6801a0ff5547a8863a99a

---
spring:
  profiles: dev
  application:
    name: springcloud-config-dev

---
spring:
  profiles: test
  application:
<<<<<<< HEAD
    name: springcloud-config-test
=======
    name: springcloud-config-test
    
>>>>>>> c349e453c9c2cebdf8a6801a0ff5547a8863a99a
