spring:
  profiles:
<<<<<<< HEAD
=======
    active: dev
>>>>>>> e57969cd97c49c5bb4b63f7d7b2c730c3d004909

---
spring:
  profiles: dev
  application:
    name: springcloud-config-dev

---
spring:
  profiles: test
  application:
    name: springcloud-config-test
<<<<<<< HEAD
=======

>>>>>>> e57969cd97c49c5bb4b63f7d7b2c730c3d004909
