spring:
  profiles: 
    active: dev

---
server:
  port: 8201
spring:
  profile: dev
  application:
    name: springcloud-provider-dept

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      #这样集群发布
      defaultZone: http://localhost:7001/eureka/,http://localhost:7003/eureka/,http://localhost:7002/eureka/

---
server:
  port: 8202
spring:
  profile: test
  application:
    name: springcloud-provider-dept

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      #这样集群发布
      defaultZone: http://localhost:7001/eureka/,http://localhost:7003/eureka/,http://localhost:7002/eureka/
