spring:
  profiles:
    active: dev

---
server:
  port: 8001
mybatis:
  type-aliases-package: com.cssf.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  profiles: dev
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db01?serverTimezone=UTC&useUnicode=true&&characterEncoding=utf-8&useSSL=false
    username: root
    password:
#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      #这样集群发布
      defaultZone: http://localhost:7001/eureka/,http://localhost:7003/eureka/,http://localhost:7002/eureka/
  instance:
    instance-id: springcloud-provider-8001 #修改Eureka上面的默认描述信息
    prefer-ip-address: false

info:
  app.name: xiaokuang-springcloud
  company.name: xiaokuang.cssf.com  #这就是一些信息格式

---
server:
  port: 8001
mybatis:
  type-aliases-package: com.cssf.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  profiles: test
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db02?serverTimezone=UTC&useUnicode=true&&characterEncoding=utf-8&useSSL=false
    username: root
    password:
#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      #这样集群发布
      defaultZone: http://localhost:7001/eureka/,http://localhost:7003/eureka/,http://localhost:7002/eureka/
  instance:
    instance-id: springcloud-provider-8001 #修改Eureka上面的默认描述信息
    prefer-ip-address: false

info:
  app.name: xiaokuang-springcloud
  company.name: xiaokuang.cssf.com  #这就是一些信息格式
